# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-25 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePartial',
            fields=[
                ('routeid', models.AutoField(db_column='RouteId', primary_key=True, serialize=False)),
                ('outsetcode', models.CharField(blank=True, db_column='OutsetCode', max_length=255, null=True)),
                ('destinationcode', models.CharField(blank=True, db_column='DestinationCode', max_length=255, null=True)),
                ('route', models.TextField(blank=True, db_column='Route', null=True)),
                ('outsetname', models.CharField(blank=True, db_column='OutsetName', max_length=255, null=True)),
                ('destinationname', models.CharField(blank=True, db_column='DestinationName', max_length=255, null=True)),
                ('outsetlon', models.CharField(blank=True, db_column='OutsetLon', max_length=255, null=True)),
                ('outsetlat', models.CharField(blank=True, db_column='OutsetLat', max_length=255, null=True)),
                ('destinationlon', models.CharField(blank=True, db_column='DestinationLon', max_length=255, null=True)),
                ('destinationlat', models.CharField(blank=True, db_column='DestinationLat', max_length=255, null=True)),
                ('shipimo', models.CharField(blank=True, db_column='ShipImo', max_length=2048, null=True)),
            ],
        ),
    ]
