# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-25 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routepartial',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='routepartial',
            table='route_partial',
        ),
    ]
